[tool.poetry]
name = "igc-repair"
version = "0.1.0"
description = ""
authors = ["amakarovskiy <amakarovskiy@ivi.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
parameterized = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
